<script lang="ts">
  import NotionBlock from "./NotionBlock.svelte";

  import "highlight.js/styles/dark.min.css";

  const blocks = {
    page: {
      object: "page",
      id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
      created_time: "2024-10-23T15:58:00.000Z",
      last_edited_time: "2024-10-23T17:20:00.000Z",
      created_by: {
        object: "user",
        id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
      },
      last_edited_by: {
        object: "user",
        id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
      },
      cover: null,
      icon: null,
      parent: {
        type: "database_id",
        database_id: "d0e26ba9-ae1e-40fe-af88-07edcf42bd76",
      },
      archived: false,
      in_trash: false,
      properties: {
        date: { id: "NX%5CQ", type: "date", date: null },
        thumbnail: { id: "WxpT", type: "files", files: [] },
        type: { id: "%60gQ~", type: "select", select: null },
        slug: {
          id: "d%5Dhq",
          type: "rich_text",
          rich_text: [
            {
              type: "text",
              text: { content: "test", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "test",
              href: null,
            },
          ],
        },
        category: { id: "ppED", type: "select", select: null },
        tags: { id: "sD%5Em", type: "multi_select", multi_select: [] },
        summary: { id: "wz%7CS", type: "rich_text", rich_text: [] },
        updatedAt: {
          id: "zyLz",
          type: "last_edited_time",
          last_edited_time: "2024-10-23T17:20:00.000Z",
        },
        author: { id: "~rC%3D", type: "people", people: [] },
        title: {
          id: "title",
          type: "title",
          title: [
            {
              type: "text",
              text: { content: "Blog Test Page", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "Blog Test Page",
              href: null,
            },
          ],
        },
        status: {
          id: "f211bdc0-ee00-4186-9a7d-f68c055ec2ee",
          type: "select",
          select: {
            id: "22460321-fea2-4c7c-b352-a674760780ac",
            name: "Private",
            color: "orange",
          },
        },
      },
      url: "https://www.notion.so/Blog-Test-Page-128065b0f5e68005a48fd9997ad0ec76",
      public_url:
        "https://oein.notion.site/Blog-Test-Page-128065b0f5e68005a48fd9997ad0ec76",
      request_id: "5330c8ee-2cda-4ab6-ad6f-f9752fe98c9a",
    },
    blocks: [
      {
        object: "block",
        id: "128065b0-f5e6-8042-8b57-e02d79a022d5",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T15:58:00.000Z",
        last_edited_time: "2024-10-23T15:58:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "heading_1",
        heading_1: {
          rich_text: [
            {
              type: "text",
              text: { content: "H1", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "H1",
              href: null,
            },
          ],
          is_toggleable: false,
          color: "default",
        },
      },
      {
        object: "block",
        id: "128065b0-f5e6-80ab-b813-eb4b1a4a1a3d",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T15:58:00.000Z",
        last_edited_time: "2024-10-23T15:59:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "heading_2",
        heading_2: {
          rich_text: [
            {
              type: "text",
              text: { content: "h2", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "h2",
              href: null,
            },
          ],
          is_toggleable: false,
          color: "default",
        },
      },
      {
        object: "block",
        id: "128065b0-f5e6-8011-9a19-d6500ab50817",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T15:59:00.000Z",
        last_edited_time: "2024-10-23T15:59:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "heading_3",
        heading_3: {
          rich_text: [
            {
              type: "text",
              text: { content: "h3", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "h3",
              href: null,
            },
          ],
          is_toggleable: false,
          color: "default",
        },
      },
      {
        object: "block",
        id: "128065b0-f5e6-80f5-917c-d9e946e178b3",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T15:59:00.000Z",
        last_edited_time: "2024-10-23T15:59:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: {
          rich_text: [
            {
              type: "text",
              text: { content: "Text ", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "Text ",
              href: null,
            },
            {
              type: "text",
              text: { content: "bold", link: null },
              annotations: {
                bold: true,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "bold",
              href: null,
            },
            {
              type: "text",
              text: { content: " ", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: " ",
              href: null,
            },
            {
              type: "text",
              text: { content: "italic ", link: null },
              annotations: {
                bold: false,
                italic: true,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "italic ",
              href: null,
            },
            {
              type: "text",
              text: { content: "underline", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: true,
                code: false,
                color: "default",
              },
              plain_text: "underline",
              href: null,
            },
          ],
          color: "default",
        },
      },
      {
        object: "block",
        id: "128065b0-f5e6-80dd-9aa6-e670e83cc4a1",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T15:59:00.000Z",
        last_edited_time: "2024-10-23T15:59:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: {
          rich_text: [
            {
              type: "text",
              text: { content: "Cut line", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: true,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "Cut line",
              href: null,
            },
          ],
          color: "default",
        },
      },
      {
        object: "block",
        id: "128065b0-f5e6-8095-b3f7-ee1afc3ae7ff",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:37:00.000Z",
        last_edited_time: "2024-10-23T16:38:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: {
          rich_text: [
            {
              type: "text",
              text: { content: "C", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "C",
              href: null,
            },
            {
              type: "text",
              text: { content: " ", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: " ",
              href: null,
            },
            {
              type: "text",
              text: { content: "C", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "gray",
              },
              plain_text: "C",
              href: null,
            },
            {
              type: "text",
              text: { content: " ", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: " ",
              href: null,
            },
            {
              type: "text",
              text: { content: "C", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "brown",
              },
              plain_text: "C",
              href: null,
            },
            {
              type: "text",
              text: { content: " ", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: " ",
              href: null,
            },
            {
              type: "text",
              text: { content: "C", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "orange",
              },
              plain_text: "C",
              href: null,
            },
            {
              type: "text",
              text: { content: " ", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: " ",
              href: null,
            },
            {
              type: "text",
              text: { content: "C", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "yellow",
              },
              plain_text: "C",
              href: null,
            },
            {
              type: "text",
              text: { content: " ", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: " ",
              href: null,
            },
            {
              type: "text",
              text: { content: "C", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "green",
              },
              plain_text: "C",
              href: null,
            },
            {
              type: "text",
              text: { content: " ", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: " ",
              href: null,
            },
            {
              type: "text",
              text: { content: "C", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "blue",
              },
              plain_text: "C",
              href: null,
            },
            {
              type: "text",
              text: { content: " ", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: " ",
              href: null,
            },
            {
              type: "text",
              text: { content: "C", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "purple",
              },
              plain_text: "C",
              href: null,
            },
            {
              type: "text",
              text: { content: " ", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: " ",
              href: null,
            },
            {
              type: "text",
              text: { content: "C", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "pink",
              },
              plain_text: "C",
              href: null,
            },
            {
              type: "text",
              text: { content: " ", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: " ",
              href: null,
            },
            {
              type: "text",
              text: { content: "C", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "red",
              },
              plain_text: "C",
              href: null,
            },
          ],
          color: "default",
        },
      },
      {
        object: "block",
        id: "128065b0-f5e6-80b4-b6e2-e28c1cf71482",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:38:00.000Z",
        last_edited_time: "2024-10-23T16:39:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: {
          rich_text: [
            {
              type: "text",
              text: { content: "B ", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "B ",
              href: null,
            },
            {
              type: "text",
              text: { content: "B", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "gray_background",
              },
              plain_text: "B",
              href: null,
            },
            {
              type: "text",
              text: { content: " ", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: " ",
              href: null,
            },
            {
              type: "text",
              text: { content: "B", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "brown_background",
              },
              plain_text: "B",
              href: null,
            },
            {
              type: "text",
              text: { content: " ", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: " ",
              href: null,
            },
            {
              type: "text",
              text: { content: "B", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "orange_background",
              },
              plain_text: "B",
              href: null,
            },
            {
              type: "text",
              text: { content: " ", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: " ",
              href: null,
            },
            {
              type: "text",
              text: { content: "B", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "yellow_background",
              },
              plain_text: "B",
              href: null,
            },
            {
              type: "text",
              text: { content: " ", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: " ",
              href: null,
            },
            {
              type: "text",
              text: { content: "B", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "green_background",
              },
              plain_text: "B",
              href: null,
            },
            {
              type: "text",
              text: { content: " ", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: " ",
              href: null,
            },
            {
              type: "text",
              text: { content: "B", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "blue_background",
              },
              plain_text: "B",
              href: null,
            },
            {
              type: "text",
              text: { content: " ", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: " ",
              href: null,
            },
            {
              type: "text",
              text: { content: "B", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "purple_background",
              },
              plain_text: "B",
              href: null,
            },
            {
              type: "text",
              text: { content: " ", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: " ",
              href: null,
            },
            {
              type: "text",
              text: { content: "B", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "pink_background",
              },
              plain_text: "B",
              href: null,
            },
            {
              type: "text",
              text: { content: " ", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: " ",
              href: null,
            },
            {
              type: "text",
              text: { content: "B", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "red_background",
              },
              plain_text: "B",
              href: null,
            },
          ],
          color: "default",
        },
      },
      {
        object: "block",
        id: "128065b0-f5e6-80e6-be46-e77933204ff3",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T15:59:00.000Z",
        last_edited_time: "2024-10-23T15:59:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: {
          rich_text: [
            {
              type: "text",
              text: { content: "Text ", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "Text ",
              href: null,
            },
            {
              type: "text",
              text: { content: "colored orange", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "orange",
              },
              plain_text: "colored orange",
              href: null,
            },
          ],
          color: "default",
        },
      },
      {
        object: "block",
        id: "128065b0-f5e6-8006-a736-dc632a20b750",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T15:59:00.000Z",
        last_edited_time: "2024-10-23T16:00:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: {
          rich_text: [
            {
              type: "text",
              text: { content: "Text ", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "Text ",
              href: null,
            },
            {
              type: "text",
              text: { content: "bg yellow", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "yellow_background",
              },
              plain_text: "bg yellow",
              href: null,
            },
          ],
          color: "default",
        },
      },
      {
        object: "block",
        id: "128065b0-f5e6-8080-b6a0-fe72ed67e6ab",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:31:00.000Z",
        last_edited_time: "2024-10-23T16:31:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: {
          rich_text: [
            {
              type: "text",
              text: { content: "Text ", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "Text ",
              href: null,
            },
            {
              type: "text",
              text: { content: "orange bg yellow", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "orange",
              },
              plain_text: "orange bg yellow",
              href: null,
            },
          ],
          color: "default",
        },
      },
      {
        object: "block",
        id: "128065b0-f5e6-8048-882a-cb27d8cd42da",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:00:00.000Z",
        last_edited_time: "2024-10-23T16:00:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: true,
        archived: false,
        in_trash: false,
        type: "table",
        table: {
          table_width: 2,
          has_column_header: false,
          has_row_header: false,
        },
        children: [
          {
            object: "block",
            id: "b0a30ded-3b1f-4145-b013-9fd778231f13",
            parent: {
              type: "block_id",
              block_id: "128065b0-f5e6-8048-882a-cb27d8cd42da",
            },
            created_time: "2024-10-23T16:00:00.000Z",
            last_edited_time: "2024-10-23T16:00:00.000Z",
            created_by: {
              object: "user",
              id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
            },
            last_edited_by: {
              object: "user",
              id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
            },
            has_children: false,
            archived: false,
            in_trash: false,
            type: "table_row",
            table_row: {
              cells: [
                [
                  {
                    type: "text",
                    text: { content: "Table 1,1", link: null },
                    annotations: {
                      bold: false,
                      italic: false,
                      strikethrough: false,
                      underline: false,
                      code: false,
                      color: "default",
                    },
                    plain_text: "Table 1,1",
                    href: null,
                  },
                ],
                [
                  {
                    type: "text",
                    text: { content: "Table 2,1", link: null },
                    annotations: {
                      bold: false,
                      italic: false,
                      strikethrough: false,
                      underline: false,
                      code: false,
                      color: "default",
                    },
                    plain_text: "Table 2,1",
                    href: null,
                  },
                ],
              ],
            },
          },
          {
            object: "block",
            id: "498d19b0-4c67-47e6-9e94-8acaccc30bea",
            parent: {
              type: "block_id",
              block_id: "128065b0-f5e6-8048-882a-cb27d8cd42da",
            },
            created_time: "2024-10-23T16:00:00.000Z",
            last_edited_time: "2024-10-23T16:00:00.000Z",
            created_by: {
              object: "user",
              id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
            },
            last_edited_by: {
              object: "user",
              id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
            },
            has_children: false,
            archived: false,
            in_trash: false,
            type: "table_row",
            table_row: {
              cells: [
                [
                  {
                    type: "text",
                    text: { content: "Table 2,1", link: null },
                    annotations: {
                      bold: false,
                      italic: false,
                      strikethrough: false,
                      underline: false,
                      code: false,
                      color: "default",
                    },
                    plain_text: "Table 2,1",
                    href: null,
                  },
                ],
                [
                  {
                    type: "text",
                    text: { content: "Table 2,2", link: null },
                    annotations: {
                      bold: false,
                      italic: false,
                      strikethrough: false,
                      underline: false,
                      code: false,
                      color: "default",
                    },
                    plain_text: "Table 2,2",
                    href: null,
                  },
                ],
              ],
            },
          },
          {
            object: "block",
            id: "fbcc265c-94bc-4e01-81ba-710790ca2a26",
            parent: {
              type: "block_id",
              block_id: "128065b0-f5e6-8048-882a-cb27d8cd42da",
            },
            created_time: "2024-10-23T16:00:00.000Z",
            last_edited_time: "2024-10-23T16:00:00.000Z",
            created_by: {
              object: "user",
              id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
            },
            last_edited_by: {
              object: "user",
              id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
            },
            has_children: false,
            archived: false,
            in_trash: false,
            type: "table_row",
            table_row: {
              cells: [
                [
                  {
                    type: "text",
                    text: { content: "Table 3,1", link: null },
                    annotations: {
                      bold: false,
                      italic: false,
                      strikethrough: false,
                      underline: false,
                      code: false,
                      color: "default",
                    },
                    plain_text: "Table 3,1",
                    href: null,
                  },
                ],
                [
                  {
                    type: "text",
                    text: { content: "Table 3,2", link: null },
                    annotations: {
                      bold: false,
                      italic: false,
                      strikethrough: false,
                      underline: false,
                      code: false,
                      color: "default",
                    },
                    plain_text: "Table 3,2",
                    href: null,
                  },
                ],
              ],
            },
          },
        ],
      },
      {
        object: "block",
        id: "128065b0-f5e6-801a-9301-d69faff6bd6e",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:00:00.000Z",
        last_edited_time: "2024-10-23T16:00:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "to_do",
        to_do: {
          rich_text: [
            {
              type: "text",
              text: { content: "TODO Off", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "TODO Off",
              href: null,
            },
          ],
          checked: false,
          color: "default",
        },
      },
      {
        object: "block",
        id: "128065b0-f5e6-8012-b26c-fd7ca1dcc366",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:00:00.000Z",
        last_edited_time: "2024-10-23T17:06:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "to_do",
        to_do: {
          rich_text: [
            {
              type: "text",
              text: { content: "TODO On", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "TODO On",
              href: null,
            },
          ],
          checked: true,
          color: "default",
        },
      },
      {
        object: "block",
        id: "128065b0-f5e6-806e-a3e3-fee6a106c383",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:00:00.000Z",
        last_edited_time: "2024-10-23T16:00:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: { rich_text: [], color: "default" },
      },
      {
        object: "block",
        id: "128065b0-f5e6-8010-8e3d-fd16a3e92e0b",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:00:00.000Z",
        last_edited_time: "2024-10-23T16:00:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "bulleted_list_item",
        bulleted_list_item: {
          rich_text: [
            {
              type: "text",
              text: { content: "Dot List", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "Dot List",
              href: null,
            },
          ],
          color: "default",
        },
      },
      {
        object: "block",
        id: "128065b0-f5e6-802e-82a7-d6298d0f7a5b",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:00:00.000Z",
        last_edited_time: "2024-10-23T16:00:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "bulleted_list_item",
        bulleted_list_item: {
          rich_text: [
            {
              type: "text",
              text: { content: "Second Item", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "Second Item",
              href: null,
            },
          ],
          color: "default",
        },
      },
      {
        object: "block",
        id: "128065b0-f5e6-80c3-8b79-fb14381069d5",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:00:00.000Z",
        last_edited_time: "2024-10-23T16:00:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: { rich_text: [], color: "default" },
      },
      {
        object: "block",
        id: "128065b0-f5e6-803b-8fcf-c13a7888d4b1",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:00:00.000Z",
        last_edited_time: "2024-10-23T16:00:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "numbered_list_item",
        numbered_list_item: {
          rich_text: [
            {
              type: "text",
              text: { content: "Numbered List", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "Numbered List",
              href: null,
            },
          ],
          color: "default",
        },
      },
      {
        object: "block",
        id: "128065b0-f5e6-803f-9f8a-e1f773f5c11c",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:00:00.000Z",
        last_edited_time: "2024-10-23T16:00:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "numbered_list_item",
        numbered_list_item: {
          rich_text: [
            {
              type: "text",
              text: { content: "Second Item", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "Second Item",
              href: null,
            },
          ],
          color: "default",
        },
      },
      {
        object: "block",
        id: "128065b0-f5e6-8038-ab86-cd305f9a7108",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:00:00.000Z",
        last_edited_time: "2024-10-23T16:00:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: { rich_text: [], color: "default" },
      },
      {
        object: "block",
        id: "128065b0-f5e6-80d7-94a0-e5cb1d101f6f",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:00:00.000Z",
        last_edited_time: "2024-10-23T16:01:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: true,
        archived: false,
        in_trash: false,
        type: "toggle",
        toggle: {
          rich_text: [
            {
              type: "text",
              text: { content: "Toggle Button", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "Toggle Button",
              href: null,
            },
          ],
          color: "default",
        },
        children: [
          {
            object: "block",
            id: "128065b0-f5e6-802f-b963-eb51b3746fd8",
            parent: {
              type: "block_id",
              block_id: "128065b0-f5e6-80d7-94a0-e5cb1d101f6f",
            },
            created_time: "2024-10-23T16:01:00.000Z",
            last_edited_time: "2024-10-23T16:01:00.000Z",
            created_by: {
              object: "user",
              id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
            },
            last_edited_by: {
              object: "user",
              id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
            },
            has_children: false,
            archived: false,
            in_trash: false,
            type: "paragraph",
            paragraph: {
              rich_text: [
                {
                  type: "text",
                  text: { content: "Toggle Content", link: null },
                  annotations: {
                    bold: false,
                    italic: false,
                    strikethrough: false,
                    underline: false,
                    code: false,
                    color: "default",
                  },
                  plain_text: "Toggle Content",
                  href: null,
                },
              ],
              color: "default",
            },
          },
        ],
      },
      {
        object: "block",
        id: "128065b0-f5e6-80af-8067-c24af43c6183",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:01:00.000Z",
        last_edited_time: "2024-10-23T16:01:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: { rich_text: [], color: "default" },
      },
      {
        object: "block",
        id: "128065b0-f5e6-809c-93d1-c091f7aa2308",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:01:00.000Z",
        last_edited_time: "2024-10-23T16:01:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "divider",
        divider: {},
      },
      {
        object: "block",
        id: "128065b0-f5e6-8057-9343-ca9af54f0345",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:01:00.000Z",
        last_edited_time: "2024-10-23T16:01:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: { rich_text: [], color: "default" },
      },
      {
        object: "block",
        id: "128065b0-f5e6-8076-871f-cd9a3d61824c",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:01:00.000Z",
        last_edited_time: "2024-10-23T16:02:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "quote",
        quote: {
          rich_text: [
            {
              type: "text",
              text: { content: "inyoung", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "inyoung",
              href: null,
            },
          ],
          color: "default",
        },
      },
      {
        object: "block",
        id: "128065b0-f5e6-8023-844c-e0cefb7d6fca",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:01:00.000Z",
        last_edited_time: "2024-10-23T16:01:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: { rich_text: [], color: "default" },
      },
      {
        object: "block",
        id: "128065b0-f5e6-8065-a165-d38c28c46d23",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:01:00.000Z",
        last_edited_time: "2024-10-23T16:01:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "callout",
        callout: {
          rich_text: [
            {
              type: "text",
              text: { content: "Callout", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "Callout",
              href: null,
            },
          ],
          icon: { type: "emoji", emoji: "💡" },
          color: "gray_background",
        },
      },
      {
        object: "block",
        id: "128065b0-f5e6-80a8-988e-f20ab162dd82",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:02:00.000Z",
        last_edited_time: "2024-10-23T16:02:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: { rich_text: [], color: "default" },
      },
      {
        object: "block",
        id: "128065b0-f5e6-80f2-875c-c31d90114465",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:02:00.000Z",
        last_edited_time: "2024-10-23T16:02:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: {
          rich_text: [
            {
              type: "text",
              text: { content: "To other page", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "To other page",
              href: null,
            },
          ],
          color: "default",
        },
      },
      {
        object: "block",
        id: "128065b0-f5e6-803b-9191-d320bf700b7f",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:02:00.000Z",
        last_edited_time: "2024-10-23T16:02:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "link_to_page",
        link_to_page: {
          type: "page_id",
          page_id: "aacb54b4-f366-42a4-8d93-4fd3ed84cc86",
        },
      },
      {
        object: "block",
        id: "128065b0-f5e6-8004-9ba0-cb98e447c4ac",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:02:00.000Z",
        last_edited_time: "2024-10-23T16:02:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: { rich_text: [], color: "default" },
      },
      {
        object: "block",
        id: "128065b0-f5e6-8092-bf29-e747269a2a66",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:02:00.000Z",
        last_edited_time: "2024-10-23T16:02:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: {
          rich_text: [
            {
              type: "text",
              text: { content: "Image Test", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "Image Test",
              href: null,
            },
          ],
          color: "default",
        },
      },
      {
        object: "block",
        id: "128065b0-f5e6-8089-9cfc-e37a5be6f55c",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:02:00.000Z",
        last_edited_time: "2024-10-23T16:02:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "image",
        image: {
          caption: [],
          type: "file",
          file: {
            url: "https://prod-files-secure.s3.us-west-2.amazonaws.com/c3058475-a9d9-4099-a751-c107f4befec2/8a14fc77-b259-4bb4-95c8-36f2a2b72d50/pixai-1799983450185366160.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45HZZMZUHI%2F20241023%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20241023T172052Z&X-Amz-Expires=3600&X-Amz-Signature=a19389be5fcf5cf630f3c6121cd43239aaf097e216587bc7010ee3e0833f1f9f&X-Amz-SignedHeaders=host&x-id=GetObject",
            expiry_time: "2024-10-23T18:20:52.444Z",
          },
        },
      },
      {
        object: "block",
        id: "128065b0-f5e6-80c3-8040-e2faad3d63e0",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:02:00.000Z",
        last_edited_time: "2024-10-23T16:02:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: { rich_text: [], color: "default" },
      },
      {
        object: "block",
        id: "128065b0-f5e6-8042-a2f8-f6ba4730b87a",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:02:00.000Z",
        last_edited_time: "2024-10-23T16:03:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: {
          rich_text: [
            {
              type: "text",
              text: { content: "File Test", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "File Test",
              href: null,
            },
          ],
          color: "default",
        },
      },
      {
        object: "block",
        id: "128065b0-f5e6-808e-8b6a-cfaf39c3e748",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:03:00.000Z",
        last_edited_time: "2024-10-23T16:03:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "file",
        file: {
          caption: [],
          type: "file",
          file: {
            url: "https://prod-files-secure.s3.us-west-2.amazonaws.com/c3058475-a9d9-4099-a751-c107f4befec2/de6699eb-49e9-430d-bba3-8ea9ce75a18c/comet.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45HZZMZUHI%2F20241023%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20241023T172052Z&X-Amz-Expires=3600&X-Amz-Signature=4279a66032e872cc8cc96930b4ce1b9acd273d04926e5e1b7b80a10a43273e95&X-Amz-SignedHeaders=host&x-id=GetObject",
            expiry_time: "2024-10-23T18:20:52.453Z",
          },
          name: "comet.txt",
        },
      },
      {
        object: "block",
        id: "128065b0-f5e6-8023-bbf2-d24cb0cdcfad",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:04:00.000Z",
        last_edited_time: "2024-10-23T16:04:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: { rich_text: [], color: "default" },
      },
      {
        object: "block",
        id: "128065b0-f5e6-802a-ae4a-caf84f8e6ed1",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:03:00.000Z",
        last_edited_time: "2024-10-23T16:04:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: {
          rich_text: [
            {
              type: "text",
              text: { content: "Tex Test", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "Tex Test",
              href: null,
            },
          ],
          color: "default",
        },
      },
      {
        object: "block",
        id: "128065b0-f5e6-8061-a50c-ddf4cd8d309d",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:03:00.000Z",
        last_edited_time: "2024-10-23T16:03:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "equation",
        equation: { expression: "|x| = 3y + sin77\\pi a" },
      },
      {
        object: "block",
        id: "128065b0-f5e6-80d8-b2a6-f57abb38b149",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:04:00.000Z",
        last_edited_time: "2024-10-23T16:04:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: {
          rich_text: [
            {
              type: "text",
              text: { content: "Inline Tex ", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "Inline Tex ",
              href: null,
            },
            {
              type: "equation",
              equation: { expression: "y=3x+d" },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "y=3x+d",
              href: null,
            },
          ],
          color: "default",
        },
      },
      {
        object: "block",
        id: "128065b0-f5e6-8054-9e00-cd407d0ba201",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:04:00.000Z",
        last_edited_time: "2024-10-23T16:04:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: { rich_text: [], color: "default" },
      },
      {
        object: "block",
        id: "128065b0-f5e6-805c-952b-e5256cf0e697",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:04:00.000Z",
        last_edited_time: "2024-10-23T16:04:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: {
          rich_text: [
            {
              type: "text",
              text: { content: "Mention Person", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "Mention Person",
              href: null,
            },
          ],
          color: "default",
        },
      },
      {
        object: "block",
        id: "128065b0-f5e6-8051-ad35-cbfb12fcee25",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T16:04:00.000Z",
        last_edited_time: "2024-10-23T16:04:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: {
          rich_text: [
            {
              type: "mention",
              mention: {
                type: "user",
                user: {
                  object: "user",
                  id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
                  name: "ein O",
                  avatar_url:
                    "https://lh3.googleusercontent.com/a-/AFdZucqbUSi6DyCO6-YVDcekb0xuOlt4LvdBnnpeg7gYpA=s100",
                  type: "person",
                  person: { email: "oein0219@gmail.com" },
                },
              },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "@ein O",
              href: null,
            },
            {
              type: "text",
              text: { content: " ", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: " ",
              href: null,
            },
          ],
          color: "default",
        },
      },
      {
        object: "block",
        id: "128065b0-f5e6-80c6-b418-dcc8f301dbd7",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T17:20:00.000Z",
        last_edited_time: "2024-10-23T17:20:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: { rich_text: [], color: "default" },
      },
      {
        object: "block",
        id: "128065b0-f5e6-802b-832d-ea0335b0bb3c",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T17:20:00.000Z",
        last_edited_time: "2024-10-23T17:20:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: {
          rich_text: [
            {
              type: "text",
              text: { content: "Code Test", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "Code Test",
              href: null,
            },
          ],
          color: "default",
        },
      },
      {
        object: "block",
        id: "128065b0-f5e6-800d-8117-d26e07b3d8f1",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T17:20:00.000Z",
        last_edited_time: "2024-10-23T17:20:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "code",
        code: {
          caption: [],
          rich_text: [
            {
              type: "text",
              text: {
                content:
                  '\nfunction main() {\n\tconsole.log("Hello, World").\n}',
                link: null,
              },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text:
                '\nfunction main() {\n\tconsole.log("Hello, World").\n}',
              href: null,
            },
          ],
          language: "typescript",
        },
      },
      {
        object: "block",
        id: "128065b0-f5e6-80ad-bf27-edc1781caf14",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T17:20:00.000Z",
        last_edited_time: "2024-10-23T17:20:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: { rich_text: [], color: "default" },
      },
      {
        object: "block",
        id: "128065b0-f5e6-80e5-8367-e3da5532e144",
        parent: {
          type: "page_id",
          page_id: "128065b0-f5e6-8005-a48f-d9997ad0ec76",
        },
        created_time: "2024-10-23T17:20:00.000Z",
        last_edited_time: "2024-10-23T17:20:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: {
          rich_text: [
            {
              type: "text",
              text: { content: "Inline Code Test ", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "Inline Code Test ",
              href: null,
            },
            {
              type: "text",
              text: { content: "This is me code", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: true,
                color: "default",
              },
              plain_text: "This is me code",
              href: null,
            },
            {
              type: "text",
              text: { content: " after code.", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: " after code.",
              href: null,
            },
          ],
          color: "default",
        },
      },
    ],
  }.blocks;

  const codeTest = {
    page: {
      object: "page",
      id: "6e24882d-eaca-46e5-827d-ac01a4edd4be",
      created_time: "2024-06-17T11:49:00.000Z",
      last_edited_time: "2024-10-14T16:14:00.000Z",
      created_by: {
        object: "user",
        id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
      },
      last_edited_by: {
        object: "user",
        id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
      },
      cover: null,
      icon: null,
      parent: {
        type: "database_id",
        database_id: "d0e26ba9-ae1e-40fe-af88-07edcf42bd76",
      },
      archived: false,
      in_trash: false,
      properties: {
        date: {
          id: "NX%5CQ",
          type: "date",
          date: { start: "2023-04-05", end: null, time_zone: null },
        },
        thumbnail: { id: "WxpT", type: "files", files: [] },
        type: {
          id: "%60gQ~",
          type: "select",
          select: {
            id: "5aff2f95-fd1e-489b-8840-bf10bc9519cb",
            name: "Post",
            color: "purple",
          },
        },
        slug: {
          id: "d%5Dhq",
          type: "rich_text",
          rich_text: [
            {
              type: "text",
              text: { content: "bash-for-loop", link: null },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "bash-for-loop",
              href: null,
            },
          ],
        },
        category: {
          id: "ppED",
          type: "select",
          select: {
            id: "cf14a391-be38-4281-84e9-c87391a17e75",
            name: "🗒️ Note",
            color: "default",
          },
        },
        tags: {
          id: "sD%5Em",
          type: "multi_select",
          multi_select: [
            {
              id: "cb112452-361a-4174-a992-0423decf786c",
              name: "Note",
              color: "red",
            },
          ],
        },
        summary: { id: "wz%7CS", type: "rich_text", rich_text: [] },
        updatedAt: {
          id: "zyLz",
          type: "last_edited_time",
          last_edited_time: "2024-10-14T16:14:00.000Z",
        },
        author: {
          id: "~rC%3D",
          type: "people",
          people: [
            {
              object: "user",
              id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
              name: "ein O",
              avatar_url:
                "https://lh3.googleusercontent.com/a-/AFdZucqbUSi6DyCO6-YVDcekb0xuOlt4LvdBnnpeg7gYpA=s100",
              type: "person",
              person: { email: "oein0219@gmail.com" },
            },
          ],
        },
        title: {
          id: "title",
          type: "title",
          title: [
            {
              type: "text",
              text: {
                content: "[코딩] Bash에서 모든 파일을 for-loop",
                link: null,
              },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text: "[코딩] Bash에서 모든 파일을 for-loop",
              href: null,
            },
          ],
        },
        status: {
          id: "f211bdc0-ee00-4186-9a7d-f68c055ec2ee",
          type: "select",
          select: {
            id: "7abc61d4-b405-480d-b699-12588755fa65",
            name: "Public",
            color: "red",
          },
        },
      },
      url: "https://www.notion.so/Bash-for-loop-6e24882deaca46e5827dac01a4edd4be",
      public_url:
        "https://oein.notion.site/Bash-for-loop-6e24882deaca46e5827dac01a4edd4be",
      request_id: "bdf09d00-0be2-4656-84c6-86f97f7e557e",
    },
    blocks: [
      {
        object: "block",
        id: "d58532d5-7f60-449d-9b3f-4b90d47c7cae",
        parent: {
          type: "page_id",
          page_id: "6e24882d-eaca-46e5-827d-ac01a4edd4be",
        },
        created_time: "2024-06-17T11:50:00.000Z",
        last_edited_time: "2024-06-17T11:50:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "code",
        code: {
          caption: [],
          rich_text: [
            {
              type: "text",
              text: {
                content:
                  'for filename in [file selector];\ndo\n echo "$filename"\ndone',
                link: null,
              },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text:
                'for filename in [file selector];\ndo\n echo "$filename"\ndone',
              href: null,
            },
          ],
          language: "bash",
        },
      },
      {
        object: "block",
        id: "d636621c-0d09-48c4-88cc-1544d2db46b4",
        parent: {
          type: "page_id",
          page_id: "6e24882d-eaca-46e5-827d-ac01a4edd4be",
        },
        created_time: "2024-06-17T11:50:00.000Z",
        last_edited_time: "2024-06-17T11:51:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: {
          rich_text: [
            {
              type: "text",
              text: {
                content:
                  "요런식으로 파일들을 돌 수 있다. 실생활 예시를 들면 아래처럼 할 수 있다.",
                link: null,
              },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text:
                "요런식으로 파일들을 돌 수 있다. 실생활 예시를 들면 아래처럼 할 수 있다.",
              href: null,
            },
          ],
          color: "default",
        },
      },
      {
        object: "block",
        id: "51e01f66-0544-4d2f-ad27-3389ecf6258a",
        parent: {
          type: "page_id",
          page_id: "6e24882d-eaca-46e5-827d-ac01a4edd4be",
        },
        created_time: "2024-06-17T11:51:00.000Z",
        last_edited_time: "2024-06-17T11:51:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "code",
        code: {
          caption: [],
          rich_text: [
            {
              type: "text",
              text: {
                content:
                  '# ogg2wav\nfor filename in *.ogg;\ndo\n ffmpeg -i "$filename" -ac 1 -ar 44100 -acodec pcm_s16le "./out/$filename.wav"\ndone',
                link: null,
              },
              annotations: {
                bold: false,
                italic: false,
                strikethrough: false,
                underline: false,
                code: false,
                color: "default",
              },
              plain_text:
                '# ogg2wav\nfor filename in *.ogg;\ndo\n ffmpeg -i "$filename" -ac 1 -ar 44100 -acodec pcm_s16le "./out/$filename.wav"\ndone',
              href: null,
            },
          ],
          language: "bash",
        },
      },
      {
        object: "block",
        id: "b83cdc31-6a2c-41c7-a1a3-f99a45b37679",
        parent: {
          type: "page_id",
          page_id: "6e24882d-eaca-46e5-827d-ac01a4edd4be",
        },
        created_time: "2024-06-17T11:51:00.000Z",
        last_edited_time: "2024-06-17T11:51:00.000Z",
        created_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        last_edited_by: {
          object: "user",
          id: "c318fc38-48b2-470e-b8e8-65dcb77907b9",
        },
        has_children: false,
        archived: false,
        in_trash: false,
        type: "paragraph",
        paragraph: { rich_text: [], color: "default" },
      },
    ],
  }.blocks;
</script>

<article class="notion-renderer">
  {#each blocks as block}
    <NotionBlock {block} />
  {/each}
</article>
